# Generated by Django 6.0.2 on 2026-04-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='🔹', max_length=10, verbose_name='Іконка (emoji)'),
        ),
    ]
