# Generated by Django 6.0.2 on 2026-05-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_category_custom_icon_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_type',
            field=models.CharField(choices=[('base', 'Вибрати з бази'), ('custom', 'Вставити свій')], default='base', max_length=10, verbose_name='Тип іконки'),
        ),
    ]
