# Generated by Django 6.0.2 on 2026-05-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_category_icon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon_type',
        ),
    ]
